cases:
  - title: Tag 1
    method: day1
    remove_comments: true
    path: data/day1.in
    params:
      year: 2020
      tuple_size: 2
  - title: Tag 1
    method: day1
    path: data/day1.in
    remove_comments: true
    params:
      year: 2020
      tuple_size: 2
  - title: Tag 1*
    method: day1
    path: data/day1.in
    remove_comments: true
    params:
      year: 2020
      tuple_size: 3
  - title: Tag 2
    method: day2
    path: data/day2.in
    remove_comments: true
    params:
      oldpolicy: true
  - title: Tag 2*
    method: day2
    path: data/day2.in
    remove_comments: true
    params:
      oldpolicy: false
  - title: Tag 3
    method: day3
    path: data/day3.in
    remove_comments: false
    params:
      directions: [ !!python/tuple [3, 1] ]
      show_path: false
  - title: Tag 3*
    method: day3
    path: data/day3.in
    remove_comments: false
    params:
      directions: [ !!python/tuple [1, 1], !!python/tuple [3, 1], !!python/tuple [5, 1], !!python/tuple [7, 1], !!python/tuple [1, 2] ]
      show_path: false
  - title: Tag 4
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: true
      show_passports: true
  - title: Tag 4*
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: false
      show_passports: true
  - title: Tag 4*
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: false
      show_passports: false
  - title: Tag 4*
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: false
      show_passports: false
  - title: Tag 4*
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: false
      show_passports: false
  - title: Tag 4*
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: false
      show_passports: false
testcases:
  - title: Tag 1
    method: day1
    remove_comments: true
    path: testdata/day1.in
    expected:
      value: 514579
    params:
      year: 2020
      tuple_size: 2
  - title: Tag 1
    method: day1
    path: testdata/day1.in
    remove_comments: true
    expected:
      value: 514579
    params:
      year: 2020
      tuple_size: 2
  - title: Tag 1*
    method: day1
    path: testdata/day1.in
    remove_comments: true
    expected:
      value: 241861950
    params:
      year: 2020
      tuple_size: 3
  - title: Tag 2
    method: day2
    path: testdata/day2.in
    remove_comments: true
    expected:
      value: 2
    params:
      oldpolicy: true
  - title: Tag 2*
    method: day2
    path: testdata/day2.in
    remove_comments: true
    expected:
      value: 1
    params:
      oldpolicy: false
  - title: Tag 3
    method: day3
    path: testdata/day3.in
    remove_comments: false
    expected:
      value: !!python/tuple [[7], 7]
    params:
      directions: [ !!python/tuple [3, 1] ]
      show_path: true
  - title: Tag 3*
    method: day3
    path: testdata/day3.in
    remove_comments: false
    expected:
      value: !!python/tuple [ [2,7,3,4,2], 336 ]
    params:
      directions: [ !!python/tuple [1, 1], !!python/tuple [3, 1], !!python/tuple [5, 1], !!python/tuple [7, 1], !!python/tuple [1, 2] ]
      show_path: false
  - title: Tag 4
    method: day4
    path: testdata/day4.in
    remove_comments: false
    expected:
      value: 2
    params:
      simple_check: true
      show_passports: true
  - title: Tag 4*
    method: day4
    path: testdata/day4.in
    remove_comments: false
    expected:
      value: 2
    params:
      simple_check: false
      show_passports: true
  - title: Tag 4*
    method: day4
    path: testdata/day4a.in
    remove_comments: false
    expected:
      value: 0
    params:
      simple_check: false
      show_passports: false
  - title: Tag 4*
    method: day4
    path: testdata/day4b.in
    remove_comments: false
    expected:
      value: 2
    params:
      simple_check: false
      show_passports: false
  - title: Tag 4*
    method: day4
    path: testdata/day4c.in
    remove_comments: false
    expected:
      value: 0
    params:
      simple_check: false
      show_passports: false
  - title: Tag 4*
    method: day4
    path: testdata/day4d.in
    remove_comments: false
    expected:
      value: 4
    params:
      simple_check: false
      show_passports: false
