info:
  description: Echte Fälle.
cases:
  - title: "Tag 1"
    index: 1
    method: day1
    remove_comments: true
    path: data/day1.in
    params:
      year: 2020
      tuple_size: 2
  - title: "Tag 1*"
    index: 1
    method: day1
    path: data/day1.in
    remove_comments: true
    params:
      year: 2020
      tuple_size: 3
  - title: "Tag 2"
    index: 2
    method: day2
    path: data/day2.in
    remove_comments: true
    params:
      oldpolicy: true
  - title: "Tag 2*"
    index: 2
    method: day2
    path: data/day2.in
    remove_comments: true
    params:
      oldpolicy: false
  - title: "Tag 3"
    index: 3
    method: day3
    path: data/day3.in
    remove_comments: false
    params:
      directions: [ !!python/tuple [3, 1] ]
      show_path: false
  - title: "Tag 3*"
    index: 3
    method: day3
    path: data/day3.in
    remove_comments: false
    params:
      directions: [ !!python/tuple [1, 1], !!python/tuple [3, 1], !!python/tuple [5, 1], !!python/tuple [7, 1], !!python/tuple [1, 2] ]
      show_path: false
  - title: "Tag 4"
    index: 4
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: true
      show_passports: true
  - title: "Tag 4*"
    index: 4
    method: day4
    path: data/day4.in
    remove_comments: false
    params:
      simple_check: false
      show_passports: true
  - title: "Tag 5"
    index: 5
    method: day5
    path: data/day5.in
    remove_comments: true
    params:
      first_part: true
      show_boardingcodes: true
  - title: "Tag 5*"
    index: 5
    method: day5
    path: data/day5.in
    remove_comments: true
    params:
      first_part: false
      show_boardingcodes: false
  - title: "Tag 6"
    index: 6
    method: day6
    path: data/day6.in
    remove_comments: true
    params:
      mode: any
  - title: "Tag 6*"
    index: 6
    method: day6
    path: data/day6.in
    remove_comments: true
    params:
      mode: all
